### ISSUE TITLE
Grafana explore tab Prometheus datasource is stuck to "loading metrics"

### ISSUE THREAD

**Issue by trif666** [zaneclaes/network-traffic-metrics#2]
Hey @zaneclaes,

First of all, thanks to you for this amazing script !

I'm trying to collect the networks metrics on my linux router by using the docker way that you propose.

Here is my docker-compose for grafana and network-traffic-metrics containers :
```
version: "3.1"

networks:
    monitoring:
        external: true

services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000          
        volumes:
            - ./grafana/data:/var/lib/grafana
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                                grafana-influxdb-08-datasource,\
                                grafana-kairosdb-datasource,\
                                grafana-piechart-panel,\
                                grafana-simple-json-datasource,\
                                grafana-worldmap-panel"
        networks:
            - db
            - monitoring
        restart: always

    network-traffic-stats:
        image: inzania/network-traffic-metrics:latest
        container_name: metrics
        privileged: true
        network_mode: host
        environment:
            - NTM_INTERFACE=enp3s0
            - NTM_PORT=8000
        restart: always
```

If i check on the browser the url : http://_host_ip_:8000 I can see that network-traffic-stats container is well started and web page displays metrics

Grafana being another container, I've used the "extra_hosts" feature (provided in docker v20.10 and above to access host ressources) to reach prometheus metrics by using url : "http://host.docker.internal:8000" in the URL prometheus datasource

Everything is going fine (tcpdump on host confirm that grafana container has well access to prometheus port) until I'm trying to us the explore tab to test queries to the metrics DB.
Indeed, when I test a simple query, I have the error "a is undefined" and the field next to the query seems stuck to "loading metrics"

Can you have already encounter this problem during your tests or am I missing something ?

Thanks,
Trif
